name: Build Frontend

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]
    paths:
      - src_ui/**
      - service.Dockerfile-ui


env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Set image tag with branch and date
      id: image_tag
      run: |
        BRANCH_NAME=${GITHUB_REF#refs/heads/}
        SAFE_BRANCH_NAME=$(echo "$BRANCH_NAME" | tr '/' '-')
        DATE=$(date +%Y-%m-%d)
        
        echo "${SAFE_BRANCH_NAME}-${DATE}" >> tags.txt
        
        if [ "$BRANCH_NAME" = "master" ]; then
        echo "latest" >> tags.txt
        fi
        
        TAGS=$(paste -sd '\n' tags.txt)
        echo "IMAGE_TAGS<<EOF" >> $GITHUB_ENV
        echo "$TAGS" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 18

    - run: npm install
      working-directory: src_ui

    - name: Build static page
      run: npm run build
      working-directory: src_ui
    
    - name: Log in to the Container registry
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-ui
        tags: ${{ env.IMAGE_TAGS }}

    - name: Build and push Docker image
      uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
      with:
        context: .
        file: ./ui.service.Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
